ALLOW_SELECT_ESCAPE = False
DEVELOPER_MODE = False
DEFAULT_QUERY_LIMIT = 25

LOG_LEVEL = "debug"

QUERY_DELEGATE_METHOD = "AIO"
S3_REDIRECT_XACCEL = None

TEXT_SEARCH_FIELD = "_txt"
TEXT_SEARCH_LANGUAGE = "english"
TEXT_SEARCH_LANGUAGE_NOSTOP = "english_nostop"

QUERY_PERMISSION = False
DEFAULT_PERMISSION_RESOURCE = False
