openapi: 3.0.0
info:
  title: API documentation as OpenAPI Specification
  description: Please change this name to your equivalent name
  version: rc0.1
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: Cookie  # name of the header, query parameter or cookie
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: []
servers:
  - url: https://staging.example.abx-ltd.net/
    description: Staging server
  - url: https://staging.example.local.abx-ltd.net/
    description: Localhost server
paths:
