DEBUG = False

REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DATABASE = 0
REDIS_USERNAME = None
REDIS_PASSWORD = None
REDIS_KEEPALIVE_INTERVAL = 60
REDIS_RETRY_ON_TIMEOUT = True

PENDING_COMMAND_TIMEOUT = 999999
COLLECT_TRACEBACK = True
