APPLICATION_NAME = "FLUVIUS_SAMPLE_SANIC_APP"
APPLICATION_SERIAL_NUMBER = 1
APPLICATION_BUILD_TIME = "1970-01-01"

SECRET_KEY = "super-secret-signing-key"
SESSION_COOKIE_SECURE = True        # Use HTTPS!
SESSION_COOKIE_HTTPONLY = True      # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = "Lax"     # CSRF protection
SESSION_COOKIE_NAME = "sanic_session"
SESSION_COOKIE_MAX_AGE = 3600       # 1 hour
