import re

RANGE_OPERATOR_KIND = "range"
DEFAULT_DELETED_FIELD = "_deleted"
OPERATOR_SEP = ":"
OPERATOR_SEP_NEGATE = "!"
RX_PARAM_SPLIT = re.compile(rf'({OPERATOR_SEP}|{OPERATOR_SEP_NEGATE})')
DEFAULT_OPERATOR = 'eq'
