export PYTHONPATH   := "../lib:../src:./"
export FLUVIUS_CONFIG_FILE := "config.ini"


help:
    just --list

## Run sanic application
run-sanic-app:
    sanic sample_app.webserver:app --dev -p 8000

run-fastapi:
    cd fastapi_app && PYTHONPATH="../../lib:../../src:../" uvicorn main:app --reload --reload-dir="../../src" --reload-dir="./"
