export PYTHONPATH   := "../lib:../src:./"
export FLUVIUS_CONFIG_FILE := "config.ini"


help:
    just --list

run APP:
    uvicorn {{APP}}:app --host 0.0.0.0 --reload --reload-dir="../src" --reload-dir="./"

